POST http://localhost:3333/auth/local/signup
Content-Type: application/json

{
    "email": "joekim@odds.team",
    "password": "12345678"
}

###
POST http://localhost:3333/auth/local/signin
Content-Type: application/json

{
    "email": "joekim@odds.team",
    "password": "12345678"
}

###
POST http://localhost:3333/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9la2ltQG9kZHMudGVhbSIsImlhdCI6MTY0NzQwMjMyNiwiZXhwIjoxNjQ3NDAzMjI2fQ.lZxKdqrsvAXye1V69WtgEsmumA6SceUNzwyHF_6YRDE